sensors:

  logical_camera_0: #Bins 8,4,3,7
    type: logical_camera
    pose:
      xyz: [5, 1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_1: #Bin 2,1,5,6 
    type: logical_camera
    pose:
      xyz: [3.0, 1.750927, 1.82]
      rpy: [0, 'pi/2', pi/2]

  logical_camera_2: #Bin 12,16,11,15
    type: logical_camera
    pose:
      xyz: [5, -1.750927, 1.82]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_3: #Bin 10,14,13,9
    type: logical_camera
    pose:
      xyz: [3.0, -1.750927, 1.82]
      rpy: [0, 'pi/2', pi/2]

  logical_camera_10: # over shelf 1 inner
    type: logical_camera
    pose:
      xyz: [3, 3.6, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_11: # over shelf 1 outer
    type: logical_camera
    pose:
      xyz: [5, -3.6, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_20: # over shelf 2 inner
    type: logical_camera
    pose:
      xyz: [3, -3.6, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_21: # over shelf 2 outer
    type: logical_camera
    pose:
      xyz: [5, 3.6, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  breakbeam_0:
    type: break_beam
    pose:
      xyz: [-0.004795, 4.492549, 0.879306]
      rpy: [0, 0, -1.557900]

  logical_camera_80: # over shelf 8 inner
    type: logical_camera
    pose:
      xyz: [-13.60, 0, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_81: # over shelf 8 outer
    type: logical_camera
    pose:
      xyz: [-15.60, 0, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_50: # over shelf 5 inner
    type: logical_camera
    pose:
      xyz: [-13.60, 3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_51: # over shelf 5 outer
    type: logical_camera
    pose:
      xyz: [-15.60, 3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_110: # over shelf 11 inner
    type: logical_camera
    pose:
      xyz: [-13.60, -3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']

  logical_camera_111: # over shelf 11 outer
    type: logical_camera
    pose:
      xyz: [-15.60, -3, 2.49]
      rpy: [0, 'pi/2', 'pi/2']


